global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'otel-collector'
    #scrape_interval: 10s
    static_configs:
      - targets: ['collector:8889']
      #- targets: ['collector:8888']

  - job_name: 'catchAllTheZips'
    static_configs:
      - targets: ['app1:8080']
