global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['collector:8889']

  - job_name: 'catchAllTheZips'
    static_configs:
      - targets: ['app1:2112']
  - job_name: 'whatsTheTemperature'
    static_configs:
      - targets: ['app2:2112']
